import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('A');
  await page.getByRole('textbox', { name: 'Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByText('-- Select --').first().click();
  await page.getByRole('option', { name: 'Admin' }).locator('span').click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('a');
  await page.getByRole('option', { name: 'Cristian Cristian Cristian' }).click();
  await page.getByText('-- Select --').click();
  await page.getByRole('option', { name: 'Enabled' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('qwer1234');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).press('CapsLock');
  await page.getByRole('textbox').nth(3).fill('T');
  await page.getByRole('textbox').nth(3).press('CapsLock');
  await page.getByRole('textbox').nth(3).fill('Timeless1231');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('T');
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('Timeless123!');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('');
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('T');
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('Timeless123!');
  await page.locator('#app div').filter({ hasText: 'Add UserUser' }).nth(1).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).press('ControlOrMeta+a');
  await page.getByRole('textbox').nth(3).fill('');
  await page.getByRole('textbox').nth(3).press('CapsLock');
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').fill('P');
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').press('CapsLock');
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').fill('');
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').press('CapsLock');
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').fill('P');
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('');
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('P');
  await page.getByRole('textbox').nth(4).press('CapsLock');
  await page.getByRole('textbox').nth(4).fill('Password123!');
  await page.locator('div').filter({ hasText: /^PasswordShould have at least 7 characters$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^PasswordShould have at least 7 characters$/ }).getByRole('textbox').fill('');
  await page.locator('div').filter({ hasText: /^PasswordShould have at least 7 characters$/ }).getByRole('textbox').press('CapsLock');
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^PasswordRequired$/ }).getByRole('textbox').fill('dswd123');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).press('ControlOrMeta+a');
  await page.getByRole('textbox').nth(4).fill('dswd123');
  await page.getByRole('button', { name: 'Save' }).click();
});